import asyncio
import os
import tempfile
import urllib.request
import xarray as xr
import numpy as np

async def fetch_and_compare():
    print("Fetching historical Nadocast output for 2024-05-16 t00z...")
    
    # Download the real prediction output from nadocast
    url = "http://data.nadocast.com/202405/20240516/t0z/nadocast_2022_models_conus_tornado_20240516_t00z_f12-35.grib2"
    
    fd, temp_path = tempfile.mkstemp(suffix=".grib2")
    os.close(fd)
    try:
        urllib.request.urlretrieve(url, temp_path)
        
        # Load the Nadocast output GRIB
        print("Loading Nadocast legacy output...")
        ds_nado = xr.open_dataset(temp_path, engine="cfgrib")
        print("\n=== Legacy Nadocast Output Grid ===")
        print(ds_nado)
        
        var_name = list(ds_nado.data_vars.keys())[0]
        nado_array = ds_nado[var_name]
        n_height, n_width = nado_array.shape
        print(f"\nLegacy Grid Shape: {n_height}x{n_width}")
        print(f"Sample probability values: {nado_array.values.flatten()[:5]}")
        
        # Now compare to our Pipeline's grid
        print("\nOur Pipeline's grid dimensions are 1059 x 1799 (as shown in Step 1 & 2 tests).")
        if n_height == 1059 and n_width == 1799:
            print("--> SANITY CHECK PASSED: The new Python spatial grid perfectly aligns with the historic Julia GRIB grid.")
        else:
            print("--> NOTE: The grids have different coordinate projections. Nadocast likely resamples before output.")
            
        print("\nTo match to the exact decimal values generated by Nadocast on this date, we will need to load your original Julia .bson models into the lgb_bridge!")
            
    finally:
        if os.path.exists(temp_path):
            os.remove(temp_path)

if __name__ == "__main__":
    asyncio.run(fetch_and_compare())
